export const SET_ALERT='SET_ALERT';
export const REMOVE_ALERT='REMOVE_ALERT';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT='LOGOUT';
export const COURSE_SAVED = 'COURSE_SAVED';
export const MODIFY_COURSE = 'MODIFY_COURSE';
export const AUTOCOMPLETE = "AUTOCOMPLETE";
export const COURSE_FAILED = 'COURSE_FAILED';
export const VIDEO_SAVED='VIDEO_SAVED';
export const VIDEO_FAILED='VIDEO_FAILED';
export const GET_COURSES = 'GET_COURSES';
export const USER_UPDATED = 'USER_UPDATED';
export const GET_VIDEO='GET_VIDEO';
export const STORE_COURSES = "STORE_COURSES";
export const MINI_COURSE_SAVED = "MINI_COURSE_SAVED";
export const MINI_COURSE_SAVE_FAILED = "MINI_COURSE_SAVE_FAILED";
export const MINI_COURSE_LOADED = "MINI_COURSE_LOADED";



